version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End build
          command: |
            npm run frontend:build
      - run:
          name: Front-End deploy
          command: |
            npm run frontend:deploy            
      - run:
          name: api Install
          command: |
            npm run api:install
      
      - run:
          name: api Build
          command: |
            npm run api:build
      - run:
          name: api deploy
          command: |
            npm run api:deploy        