version: 2.1
orbs:
# used to setup env need by our app
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
brcanhes:
  only:
    -main   
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - eb/setup
      - run:
      #install all dependencies in our front end
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
      #build our front end app
          name: Front-End build
          command: |
            npm run frontend:build
      - run:
       #deploy our front end app
          name: Front-End deploy
          command: |
            npm run frontend:deploy            
      - run:
      #install all dependencies in our front end
          name: api Install
          command: |
            npm run api:install
      
      - run:
       #build our api app
          name: api Build
          command: |
            npm run api:build
      - run:
      #deploy our apiapp
          name: api deploy
          command: |
            npm run api:deploy        